---
title: 在 "Try" 语句中，"Catch" 不能出现在 "Finally" 之后
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: 327bec408905c927c5232297f87b8f54ec941beb
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 09/23/2020
ms.locfileid: "91074558"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>在 "Try" 语句中，"Catch" 不能出现在 "Finally" 之后

`Catch` 语句出现在代码中结束 `Finally` 语句块的 `Try` 之后。 `Catch` 必须出现在 `Try...Catch...Finally` 语句块之内。  
  
 **错误 ID：** BC30379  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
1. 将 `Catch` 语句移到代码中更合适的位置。  
  
## <a name="see-also"></a>请参阅

- [尝试 .。。Catch .。。Finally 语句](../language-reference/statements/try-catch-finally-statement.md)
