---
title: 永远不会到达“Catch”块；<exception> 已在上面同一个 Try 语句中处理
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 5133bfd9b4471350691407dee09feec2d3af444a
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 09/23/2020
ms.locfileid: "91084549"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>永远不会到达“Catch”块；\<exception> 已在上面同一个 Try 语句中处理

无法达到代码中的 `Catch` 块，因为它已经在前面的 `Try` 块中得到处理。  
  
默认情况下，此消息是一个警告。 有关隐藏警告或将警告视为错误的详细信息，请参阅 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)。
  
 **错误 ID：** BC42031  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
- 删除多余的语句。  
  
## <a name="see-also"></a>请参阅

- [如何使用 try/catch 块捕获异常](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [使用用户筛选的异常处理程序](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [尝试 .。。Catch .。。Finally 语句](../language-reference/statements/try-catch-finally-statement.md)
